# Generated by Django 3.1.4 on 2020-12-18 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Naira Price', max_length=20)),
                ('exchange_rate', models.IntegerField(default=365)),
            ],
        ),
        migrations.CreateModel(
            name='kycinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=50)),
                ('home_address', models.CharField(default='None', max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('personal_ids', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('dob', models.DateField(default='12/12/2000')),
                ('is_verified', models.BooleanField(default=False)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
